version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
