# web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default

spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
