name: Build and Push to ECR

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      
    - name: Get the Git commit SHA
      id: commit_sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Build Docker image
      run: docker build -t app:${{ steps.commit_sha.outputs.sha }} .

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 185124489034.dkr.ecr.us-east-1.amazonaws.com

    - name: Tag Docker image
      run: docker tag app:${{ steps.commit_sha.outputs.sha }}  185124489034.dkr.ecr.us-east-1.amazonaws.com/app:${{ steps.commit_sha.outputs.sha }}

    - name: Push Docker image to ECR
      run: docker push 185124489034.dkr.ecr.us-east-1.amazonaws.com/app:${{ steps.commit_sha.outputs.sha }}


    - name: Update Deployment YAML with Git commit SHA
      run: |
        sed -i "s|image: .*|image: 185124489034.dkr.ecr.us-east-1.amazonaws.com/app:${{ steps.commit_sha.outputs.sha }}|" ./manifests/web-deployment.yml
    - name: Commit and push changes
      run: |
        git config --local user.email "selvinjethu@gmail.com"
        git config --local user.name "GitHub Action"
        git add ./manifests/web-deployment.yml
        git commit -m "Update image tag in Deployment YAML"
        git push
